config/routes.rb
Metube::Application.routes.draw do
  
  root 'videos#show_all'

  get '/videos/:video_name' => 'videos#show',     as: 'video'
  get '/videos'             => 'videos#show_all', as: 'videos'
  get '/videos/:video_one_name/:video_two_name' => 'videos#show_two', as: 'show_two'
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clips_controller.rb
class ClipsController < ApplicationController

	def show_seinfield
		@clips = {
			title:    "Seinfield Clip #1",
			subtitle: "These Pretzels are making me thirsty!",
			video_id: "9RK99NAJyeg"
		}
	end

	def show_friends
		@clips = {
			title:    "Friends Clip #1",
			subtitle: "Smelly Cat",
			video_id: 'W7jlGRq8xZ4'
		}
	end

	def show_parks
		@clips = {
			title:    "Parks & Rec Clip #1",
			subtitle: "Latin Flower Names",
			video_id: "pbVNq-B70ho"
		}
	end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

	def show_gladiator
		@movie = {
			title:       "Gladiator",
			subtitle:    "Crowe shows everyone what's up",
			description: "Russel Crowe is a boss in this video",
			video_id:    "FI1ylg4GKv8"
		}
	end

	def show_matilda
		@movie = {
			title:       "Matilda",
			subtitle:    "Bruce's brownie scene",
			description: "This movie is just great. Who agrees?",
			video_id:    "EVWOQwZENBg"
		}
	end

	def show_klowns
		@movie = {
			title:       "Killer Klowns from Outter Space",
			subtitle:    "In Space No One Can Eat Ice Cream!",
			description: "Killer Balloon Dog is Krazy!",
			video_id:    "tUD_LjVoo_Q"
		}
	end

	def show_waterboy
		@movie = {
			title:       "The Waterboy",
			subtitle:    "Water Sucks....",
			description: "...Gatorade is better",
			video_id:    "mu9VA3pTEzs"
		}
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home

	end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def show_all
    @params = params
  end

  def show

    video_name = params[:video_name]

    videos = {
      'gladiator' => {
        title:       "Gladiator",
        subtitle:    "Crowe shows everyone what's up",
        description: "Russel Crowe is a boss in this video",
        video_id:    "FI1ylg4GKv8"
      },

      'matilda' => {
        title:       "Matilda",
        subtitle:    "Bruce's brownie scene",
        description: "This movie is just great. Who agrees?",
        video_id:    "EVWOQwZENBg"
      },

      'klowns' => {
        title:       "Killer Klowns from Outer Space",
        subtitle:    "In Space No One Can Eat Ice Cream!",
        description: "Killer Balloon Dog is Krazy!",
        video_id:    "tUD_LjVoo_Q"
      },

      'waterboy' => {
        title:       "The Waterboy",
        subtitle:    "Water Sucks....",
        description: "...Gatorade is better",
        video_id:    "mu9VA3pTEzs"
      },

      'seinfeld' => {
        title:    "Seinfeld Clip #1",
        subtitle: "These Pretzels are making me thirsty!",
        video_id: "9RK99NAJyeg"
      },
    
      'friends' => {
        title:    "Friends Clip #1",
        subtitle: "Smelly Cat",
        video_id: 'W7jlGRq8xZ4'
      },

      'parks' => {
        title:    "Parks & Rec Clip #1",
        subtitle: "Latin Flower Names",
        video_id: "pbVNq-B70ho"
      }
    }

    @video = videos[video_name]

  end

  def show_two

    video_one_name = params[:video_one_name]
    video_two_name = params[:video_two_name]

    videos = {
      'gladiator' => {
        title:       "Gladiator",
        subtitle:    "Crowe shows everyone what's up",
        description: "Russel Crowe is a boss in this video",
        video_id:    "FI1ylg4GKv8"
      },

      'matilda' => {
        title:       "Matilda",
        subtitle:    "Bruce's brownie scene",
        description: "This movie is just great. Who agrees?",
        video_id:    "EVWOQwZENBg"
      },

      'klowns' => {
        title:       "Killer Klowns from Outer Space",
        subtitle:    "In Space No One Can Eat Ice Cream!",
        description: "Killer Balloon Dog is Krazy!",
        video_id:    "tUD_LjVoo_Q"
      },

      'waterboy' => {
        title:       "The Waterboy",
        subtitle:    "Water Sucks....",
        description: "...Gatorade is better",
        video_id:    "mu9VA3pTEzs"
      },

      'seinfeld' => {
        title:    "Seinfeld Clip",
        subtitle: "These Pretzels are making me thirsty!",
        video_id: "9RK99NAJyeg"
      },
    
      'friends' => {
        title:    "Friends",
        subtitle: "Smelly Cat",
        video_id: 'W7jlGRq8xZ4'
      },

      'parks' => {
        title:    "Parks & Rec",
        subtitle: "Latin Flower Names",
        video_id: "pbVNq-B70ho"
      }
    }

    @video_one = videos[video_one_name]
    @video_two = videos[video_two_name]

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/Clips/show_friends.html.erb
<h1><%= @clips[:title] %></h1>

<h3><%= @clips[:subtitle] %></h3>

<iframe width="420" height="315" src="//www.youtube.com/embed/<%= @clips[:video_id] %>" frameborder="0" allowfullscreen></iframe>

app/views/Clips/show_parks.html.erb
<h1><%= @clips[:title] %></h1>

<h3><%= @clips[:subtitle] %></h3>

<iframe width="420" height="315" src="//www.youtube.com/embed/<%= @clips[:video_id] %>" frameborder="0" allowfullscreen></iframe>

app/views/Clips/show_seinfield.html.erb
<h1><%= @clips[:title] %></h1>

<h3><%= @clips[:subtitle] %></h3>

<iframe width="420" height="315" src="//www.youtube.com/embed/<%= @clips[:video_id] %>" frameborder="0" allowfullscreen></iframe>

app/views/Movies/show_gladiator.html.erb
<h1><%= @movie[:title] %></h1>

<h3><%= @movie[:subtitle] %></h3>

<iframe width="420" height="315" src="//www.youtube.com/embed/<%= @movie[:video_id] %>" frameborder="0" allowfullscreen></iframe>

<p><%= @movie[:description] %></p>

app/views/Movies/show_klowns.html.erb
<h1><%= @movie[:title] %></h1>

<h3><%= @movie[:subtitle] %></h3>

<iframe width="420" height="315" src="//www.youtube.com/embed/<%= @movie[:video_id] %>" frameborder="0" allowfullscreen></iframe>

<p><%= @movie[:description] %></p>

app/views/Movies/show_matilda.html.erb
<h1><%= @movie[:title] %></h1>

<h3><%= @movie[:subtitle] %></h3>

<iframe width="420" height="315" src="//www.youtube.com/embed/<%= @movie[:video_id] %>" frameborder="0" allowfullscreen></iframe>

<p><%= @movie[:description] %></p>

app/views/Movies/show_waterboy.html.erb
<h1><%= @movie[:title] %></h1>

<h3><%= @movie[:subtitle] %></h3>

<iframe width="420" height="315" src="//www.youtube.com/embed/<%= @movie[:video_id] %>" frameborder="0" allowfullscreen></iframe>

<p><%= @movie[:description] %></p>

app/views/Videos/show.html.erb
<h1><%= @video[:title] %></h1>

<h3><%= @video[:subtitle] %></h3>

<iframe width="420" height="315" src="//www.youtube.com/embed/<%= @video[:video_id] %>" frameborder="0" allowfullscreen></iframe>

<p><%= @video[:description] %></p>

app/views/Videos/show_all.html.erb
<h1>MeTube Video List</h1>
<ul>
  <li><%= link_to "Gladiator", video_path('gladiator') %></li>
  <li><%= link_to "Matilda", video_path('matilda') %></li>
  <li><%= link_to "Killer Klowns", video_path('klowns') %></li>
  <li><%= link_to "The Waterboy", video_path('waterboy') %></li>
  <li><%= link_to "Seinfeld", video_path('seinfeld') %></li>
  <li><%= link_to "Friends", video_path('friends') %></li>
  <li><%= link_to "Parks", video_path('parks') %></li>
</ul>

<h2>View 2 Videos at Once!</h2>
<ul>
	<li><%= link_to "Gladiator & Matilda", show_two_path('gladiator','matilda')  %></li>
	<li><%= link_to "Killer Klowns & Friends", show_two_path('klowns','friends') %> </li>
	<li><%= link_to "Friends & The Waterboy", show_two_path('friends', 'waterboy') %></li>
</ul>

app/views/Videos/show_two.html.erb
<h1><%= @video_one[:title] %></h1>

<h3><%= @video_one[:subtitle] %></h3>

<iframe width="420" height="315" src="//www.youtube.com/embed/<%= @video_one[:video_id] %>" frameborder="0" allowfullscreen></iframe>

<p><%= @video_one[:description] %></p>

</br>
</br>

<h1><%= @video_two[:title] %></h1>

<h3><%= @video_two[:subtitle] %></h3>

<iframe width="420" height="315" src="//www.youtube.com/embed/<%= @video_two[:video_id] %>" frameborder="0" allowfullscreen></iframe>

<p><%= @video_two[:description] %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Metube</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>MeTube Home Directory</h1>

<h2>Movies</h2>

<ul>
	<li><%= link_to "Gladiator",   gladiator_path %></li>
	<li><%= link_to "Matilda",     matilda_path %></li>
	<li><%= link_to "Killer Klowns from Outer Space", klowns_path %></li>
	<li><%= link_to "The Waterboy", waterboy_path %></li>
</ul>


<h2>Clips</h2>
	<ul>
		<li><%= link_to "Seinfield",    seinfield_path %></li>
		<li><%= link_to "Friends",      friends_path %></li>
		<li><%= link_to "Parks & Rec",  parks_path %></li>
	</ul>